body {
    background-image: url(/src/assets/images/background.png);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: auto 100%;
    margin: 0;
    background-position-x: left;
}

.esquerda-cadastrese {
    width: 979px;
    height: 617px;
    flex-shrink: 0;
    border-radius: 8px;
    border: 2px solid rgba(0, 0, 0, 0.14);
    background: #FFF;
    backdrop-filter: blur(54.65px);
    filter: drop-shadow(30px 30px rgba(217, 217, 217, 0.28));
}

.container-cadastrese {
    display: flex;
    justify-content: space-between;
    /* Manter as colunas lado a lado */
}

.espacamento {
    padding: 1.9rem;
}

.cabecalho {
    width: 100;
    flex-shrink: 0;
    color: var(--Azul-Principal, #0C194E);
    font-feature-settings: 'liga' off, 'clig' off;
    font-family: Poppins;
    font-size: 24px;
    font-style: normal;
    font-weight: 600;
    line-height: 12px;
    /* 50% */
}

.cabecalho-cadastro {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: center;
    justify-content: initial;
    gap: 20rem
}


.dados {
    width: 357px;
    height: 13px;
    flex-shrink: 0;
    color: var(--Verde-Principal, #00C677);
    font-feature-settings: 'liga' off, 'clig' off;
    font-family: Poppins;
    font-size: 18px;
    font-style: normal;
    font-weight: 600;
    line-height: 12px;
    margin-top: -1.1rem;
    /* 66.667% */
}

.container-inputs,
.container-inputs2 {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-top: 3rem;
    width: 48%;
    /* Ajusta a largura das colunas para que se ajustem lado a lado */
}

.input {
    width: 420px;
    height: 52px;
    flex-shrink: 0;
    border-radius: var(--Corner-Extra-small, 4px);
    border: 0.5px solid rgba(0, 0, 0, 0.39);
    background: #FFF;
}

.etapas {
    width: 423px;
    height: 56px;
    flex-shrink: 0;
    border-radius: 50px;
    background: var(--Azul-Principal, #0C194E);
    color: #FFF;
    font-feature-settings: 'liga' off, 'clig' off;
    font-family: Poppins;
    font-size: 16px;
    font-style: normal;
    font-weight: 600;
    line-height: 12px;
    border: var(--Azul-Principal, #0C194E);
    margin-top: 1rem;
}

.etapas1 {
    width: 423px;
    height: 56px;
    flex-shrink: 0;
    border-radius: 50px;
    background: var(--Azul-Principal, #0C194E);
    color: #FFF;
    font-feature-settings: 'liga' off, 'clig' off;
    font-family: Poppins;
    font-size: 16px;
    font-style: normal;
    font-weight: 600;
    line-height: 12px;
    border: var(--Azul-Principal, #0C194E);
    margin-top: 1.78rem;
}

.etapas:hover{
    background: #FFF;
    border: 1px solid var(--Azul-Principal, #0C194E);
    color: #0C194E;
    transition: 0.5s;
}

.revisarInfo {
    border: none;
    background-color: #FFF;
    color: var(--Verde-Principal, #00C677);
    font-feature-settings: 'liga' off, 'clig' off;
    font-family: Poppins;
    font-size: 16px;
    font-style: normal;
    font-weight: 500;
    line-height: 12px; /* 75% */
}
